//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public caja()
        {
            this.turno = new HashSet<turno>();
        }
    
        public int codi_caja { get; set; }
        public string nomb_caja { get; set; }
        public string esta_caja { get; set; }
        public string obse_caja { get; set; }
    
        public virtual ICollection<turno> turno { get; set; }
    }
}
