//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pago
    {
        public int idet_pago { get; set; }
        public System.TimeSpan tiem_tota { get; set; }
        public double tota_deta { get; set; }
        public int nume_fact { get; set; }
        public int codi_serv { get; set; }
        public int codi_pago { get; set; }
    
        public virtual pago pago { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
