//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parqueaderoEntities : DbContext
    {
        public parqueaderoEntities()
            : base("name=parqueaderoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caja> caja { get; set; }
        public DbSet<cliente> cliente { get; set; }
        public DbSet<detalle_pago> detalle_pago { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<pago> pago { get; set; }
        public DbSet<privilegio_cliente> privilegio_cliente { get; set; }
        public DbSet<servicio> servicio { get; set; }
        public DbSet<tipo_vehiculo> tipo_vehiculo { get; set; }
        public DbSet<vehiculo> vehiculo { get; set; }
        public DbSet<lista_negra> lista_negra { get; set; }
        public DbSet<turno> turno { get; set; }
        public DbSet<ubicacion> ubicacion { get; set; }
    }
}
