//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_vehiculo
    {
        public tipo_vehiculo()
        {
            this.vehiculo = new HashSet<vehiculo>();
        }
    
        public int tipo_vehi { get; set; }
        public string nomb_vehi { get; set; }
        public double tari_vehi { get; set; }
    
        public virtual ICollection<vehiculo> vehiculo { get; set; }
    }
}
