//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno
    {
        public int codi_turn { get; set; }
        public int codi_empl { get; set; }
        public int codi_caja { get; set; }
        public System.DateTime fech_inic { get; set; }
        public Nullable<System.DateTime> fech_fina { get; set; }
        public double mont_inic { get; set; }
        public string desc_turn { get; set; }
    
        public virtual caja caja { get; set; }
        public virtual empleado empleado { get; set; }
    }
}
